// <auto-generated />
namespace ShowRegSys.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class zmiana : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(zmiana));
        
        string IMigrationMetadata.Id
        {
            get { return "201311191231416_zmiana"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
