// <auto-generated />
namespace ShowRegSys.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class DodanieKlas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DodanieKlas));
        
        string IMigrationMetadata.Id
        {
            get { return "201311271349202_DodanieKlas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
