// <auto-generated />
namespace ShowRegSys.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class create1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(create1));
        
        string IMigrationMetadata.Id
        {
            get { return "201310211138195_create1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
