namespace ShowRegSys.Migrations
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Data.Entity.Migrations;
    using System.Linq;
    using ShowRegSys.Models;

    internal sealed class Configuration : DbMigrationsConfiguration<ShowRegSys.DAL.ShowContext>
    {
        public Configuration()
        {
            AutomaticMigrationsEnabled = false;
        }

        protected override void Seed(ShowRegSys.DAL.ShowContext context)
        {
            var pkrs = new List<Pkr>
            {
                new Pkr { Name = "PKR.I", Number = 1 },
                new Pkr { Name = "PKR.II", Number = 2 },
                new Pkr { Name = "PKR.III", Number = 3 },
                new Pkr { Name = "PKR.IV", Number = 4 },
                new Pkr { Name = "PKR.V", Number = 5 },
                new Pkr { Name = "PKR.VI", Number = 6 },
                new Pkr { Name = "PKR.VII", Number = 7 },
                new Pkr { Name = "PKR.VIII", Number = 8 },
                new Pkr { Name = "PKR.IX", Number = 9 },
                new Pkr { Name = "PKR.X", Number = 10 }
            };
            pkrs.ForEach(p => context.Pkrs.AddOrUpdate(a => a.Name, p));
            context.SaveChanges();
            


            var organizer = new List<Organizer>
            {
                new Organizer { Name = "Bêdzin", City = "Bêdzin",
                    Address = "Ul. Rubna 1", Email = "biuro@zkwp.bedzin.pl",
                    Telephone = "32-263-70-05", 
                    BankAccount = "Alior Bank 83 2490 0005 0000 4500 6028 8749" },
                new Organizer { Name = "Bia³ystok", City = "Bia³ystok",
                    Address = "Ul. Jurowiecka 33", Email = "biuro@zkwp.bialystok.pl",
                    Telephone = "85-653 77 95",
                    BankAccount = "PKO BP S.A. I O/Bia³ystok 59 1020 1332 0000 1502 0025 9333" },
                new Organizer { Name = "Bielsko-Bia³a", City = "Bielsko-Bia³a",
                    Address = "Ul. Sowieskiego 132", Email = "zkwpbielsko@gmail.com",
                    Telephone = "33-812-63-89",
                    BankAccount = "Pekao S.A. O/Bielsko-Bia³a 34 1240 6449 1111 0010 5313 7101" },
                new Organizer { Name = "Bydgoszcz", City = "Bydgoszcz",
                    Address = "Ul. U³añska 4a", Email = "zkwpbydgoszcz@onet.pl",
                    Telephone = "52-328-49-07",
                    BankAccount = "PeKaO SA O/Bydgoszcz 38 1240 3493 1111 0000 4305 7832" },
                new Organizer { Name = "Bytom", City = "Bytom", 
                    Address = "Ul. Mickiewicza 13", Email = "zkwp_bytom@op.pl",
                    Telephone = "32-281-73-84",
                    BankAccount = "BZ Wroc³aw I O/Bytom 84 1090 2011 0000 0005 3200 0037" },
                new Organizer { Name = "Chojnice", City = "Chojnice",
                    Address = "Pl. Jagielloñski 2", Email = "chojnice@zkwp.pl",
                    Telephone = "52-397-06",
                    BankAccount = "Bank Spó³dzielczy w Chojnicach 51 8146 0003 0000 0211 2000 0010" },
                new Organizer { Name = "Chorzów", City = "Chorzów",
                    Address = "Ul. Powstañców 41", Email = "biuro@zkwp-chorzow.net",
                    Telephone = "32-241-08-30",
                    BankAccount = "ING BSK O/Chorzów 74 1050 1243 1000 0010 0000 2764" },
                new Organizer { Name = "Czêstochowa", City = "Czêstochowa",
                    Address = "Ul. Sobieskiego 19a lok. 3", Email = "info@zkwp-czestochowa.org.pl",
                    Telephone = "34-324-46-13",
                    BankAccount = "Bank Millenium, 63 1160 2202 0000 0001 7562 5445" },
                new Organizer { Name = "Gdynia", City = "Gdynia",
                    Address = "Ul. Bohaterów Starówki Warszawskiej 6", Email = "gdynia@zkwp.pl",
                    Telephone = "58-622-64-42",
                    BankAccount = "PKO SA I O/Gdynia 92 1240 1239 1111 0000 1642 8100" },
                new Organizer { Name = "Gorzów Wlkp.", City = "Gorzów Wlkp.",
                    Address = "Ul. Kosynierów Gdyñskich 98", Email = "biuro@kynologia.gorzow.pl",
                    Telephone = "95-735-03-45",
                    BankAccount = "Polbank EFG 85 2340 0009 0610 2460 0000 0051" },
                new Organizer { Name = "Grudz¹dz", City = "Grudz¹dz",
                    Address = "Ul. Moniuszki 19", Email = "zkwp.grudz@wp.pl",
                    Telephone = "56-426-64-12",
                    BankAccount = "Bank BG¯ 81 2030 0045 1110 0000 0187 2590" },
                new Organizer { Name = "Inowroc³aw", City = "Inowroc³aw",
                    Address = "Ul. Dworcowa 25", Email = "zw_kyn_ino1@poczta.onet.pl",
                    Telephone = "52-566-24-42",
                    BankAccount = "BZ WBK SA O/I-w 26 1090 1069 0000 0000 0701 4199" },
                new Organizer { Name = "Jelenia Góra", City = "Jelenia Góra",
                    Address = "Ul. 1 Maja 67", Email = "jeleniagora@zkwp.pl",
                    Telephone = "75-752-57-15",
                    BankAccount = "PKO BP 88 1020 2124 0000 8602 0006 8585" },
                new Organizer { Name = "Kalisz", City = "Kalisz",
                    Address = "Al. Wojska Polskiego 10B", Email = "zk-kalicz@o2.pl",
                    Telephone = "62-757-43-15",
                    BankAccount = "WBK O/Kalisz 22 1090 1128 0000 0000 1201 5716" },
                new Organizer { Name = "Katowice", City = "Katowice",
                    Address = "Ul. Koœciuszki 42", Email = "info@zkwp.katowice.pl",
                    Telephone = "32-251-67-80",
                    BankAccount = "PKO BP II O/Katowice 05 1020 2313 0000 3802 0019 7871" },
                new Organizer { Name = "Kielce", City = "Kielce",
                    Address = "Ul. Œl¹ska 10", Email = "kielce@zkwp.pl",
                    Telephone = "41-368-74-68",
                    BankAccount = "ING BS 60 1050 1416 1000 0023 1575 9072" },
                new Organizer { Name = "Koszalin", City = "Koszalin",
                    Address = "Ul. Jana z Kolna 26/5", Email = "biuro@zkwp-koszalin.pl",
                    Telephone = "94-348-06-86", 
                    BankAccount = "PKO SA II O/Koszalin 95 1240 3653 1111 0000 4188 3468" },
                new Organizer { Name = "Kraków", City = "Kraków",
                    Address = "Ul. ¯ywiecka 36", Email = "biuro@zkwpkrakow.pl",
                    Telephone = "12-266-70-85",
                    BankAccount = "Bank Pekao SA 80 1240 4432 1111 0000 4722 3693" },
                new Organizer { Name = "Krosno", City = "Krosno",
                    Address = "Ul. Betleja 1a", Email = "rasowe@interia.pl",
                    Telephone = "13-436-85-74",
                    BankAccount = "PKO BP O/Krosno 19 1020 2964 0000 6502 0003 4587" },
                new Organizer { Name = "Legionowo", City = "Legionowo",
                    Address = "Ul. Jagielloñska 20", Email = "biuro@zkwp-legionowo.pl",
                    Telephone = "22-784-27-66",
                    BankAccount = "ING BSK SA O/Legionowo 43 1050 1012 1000 0022 1151 3888" },
                new Organizer { Name = "Legnica", City = "Legnica",
                    Address = "Ul. Libana 10", Email = "legnica@zkwp.pl",
                    Telephone = "76-852-35-83",
                    BankAccount = "Kredyt Bank S.A. O/Legnica 83 1500 1504 1215 0000 4148 0000" },
                new Organizer { Name = "Leszno", City = "Leszno",
                    Address = "Ul. Œrednia 9", Email = "zkwpleszno@gmail.com",
                    Telephone = "65-529-59-92",
                    BankAccount = "PKO SA O/Leszno 77 1240 1499 1111 0000 1881 9014" },
                new Organizer { Name = "Lublin", City = "Lublin",
                    Address = "Ul. Dolna Panny Marii 53", Email = "biuro@zk.lublin.pl",
                    Telephone = "81-532-75-50",
                    BankAccount = "PKO II O/Lublin 35 1020 3150 0000 3702 0002 8795" },
                new Organizer { Name = "£ódŸ", City = "£ódŸ",
                    Address = "Al. Koœciuszki 48", Email = "lodz@zkwp.pl",
                    Telephone = "42-637-62-62",
                    BankAccount = "PKO SA VI O/£ódŸ 35 1240 3031 1111 0000 3426 6805" },
                new Organizer { Name = "Nowy S¹cz", City = "Nowy S¹cz",
                    Address = "Ul. Broniewskiego 26", Email = "wystawans@gmail.com",
                    Telephone = "18-442-02-37",
                    BankAccount = "PKO BP SA Nowy S¹cz 43 1020 3453 0000 8602 0008 1281" },
                new Organizer { Name = "Nowy Targ", City = "Nowy Targ",
                    Address = "Ul. PArkowa 14", Email = "zkwpnt@wp.pl",
                    Telephone = "18-264-01-66",
                    BankAccount = "63 1240 5136 1111 0000 5221 5427" },
                new Organizer { Name = "Olsztyn", City = "Olsztyn",
                    Address = "Ul. Warmiñska 4", Email = "olsztyn@zkwp.pl",
                    Telephone = "89-535-14-41",
                    BankAccount = "ING BSK O/Olsztyn 22 1050 1807 1000 0022 5330 5441" },
                new Organizer { Name = "Opole", City = "Opole",
                    Address = "Ul. 1 Maja 92", Email = "zkwpopole@zkwp-opole.pl",
                    Telephone = "7-453-72-86",
                    BankAccount = "Citi Handlowy S.A. 75 1030 0019 0109 8530 0037 6685" },
                new Organizer { Name = "P³ock", City = "P³ock",
                    Address = "Ul. Jasienna 10", Email = "biuro@zkwpplock.pl",
                    Telephone = "24-263-68-38",
                    BankAccount = "LUKAS Bank 04 1940 1076 3087 8639 0000 0000" },
                new Organizer { Name = "Poznañ", City = "Poznañ",
                    Address = "Ul. Piwoniowa 16", Email = "poznan@zkwp.pl",
                    Telephone = "61-852-27-84", 
                    BankAccount = "BZ WBK SA III O/P-ñ 49 1090 1359 0000 0000 3501 8426" },
                new Organizer { Name = "Przemyœl", City = "Przemyœl",
                    Address = "Ul. Lwowska 71", Email = "zkwpprzemysl@op.pl",
                    Telephone = "16-678-85-82",
                    BankAccount = "KB S.A. O/Przemyœl 74 1500 1634 1216 3005 1386 0000" },
                new Organizer { Name = "Racibórz", City = "Racibórz",
                    Address = "Ul. Ks. Londzina 49", Email = "zkwp-raciborz@world.pl",
                    Telephone = "32-415-59-44",
                    BankAccount = "ING BSK O/Racibórz 62 1050 1328 1000 0022 4267 4410" },
                new Organizer { Name = "Radom", City = "Radom",
                    Address = "Ul. Wernera 29/31", Email = "zkwp@home.pl",
                    Telephone = "48-363-16-70",
                    BankAccount = "BS O/Radom 77 9147 0009 0000 0853 2000 0001" },
                new Organizer { Name = "Rybnik", City = "Rybnik",
                    Address = "Ul. Jankowicka 3", Email = "zk-rybnik@wp.pl",
                    Telephone = "32-423-58-52",
                    BankAccount = "Kredyt Bank SA I/Rybnik 60 1500 1214 1212 1001 7988 0000" },
                new Organizer { Name = "Rzeszów", City = "Rzeszów",
                    Address = "ul. ¯wirki i Wigury 8", Email = "biuro@zkwp.rzeszow.pl",
                    Telephone = "17-854-17-40",
                    BankAccount = "PKO BP SA 11 1020 4391 0000 6302 0079 8694" },
                new Organizer { Name = "S³upsk", City = "S³upsk", 
                    Address = "Ul. Lutos³awskiego 33", Email = "info@zkwp.eslupsk.pl",
                    Telephone = "59-841-47-84",
                    BankAccount = "49 1020 4649 0000 7702 0065 8914" },
                new Organizer { Name = "Sopot", City = "Sopot",
                    Address = "Al. Niepodleg³oœci 825", Email = "sopot@zkwp.pl",
                    Telephone = "58-551-33-69",
                    BankAccount = "ING BSK SA 71 1050 1764 1000 0091 3316 5309" },
                new Organizer { Name = "Szczecin", City = "Szczecin",
                    Address = "Al. Papie¿a Jana Paw³a II nr 44", Email = "szczecin@zkwp.pl",
                    Telephone = "91-434-65-09",
                    BankAccount = "PKO BP SA II O/Szczecin 58 1020 4795 0000 9602 0155 3585" },
                new Organizer { Name = "Toruñ", City = "Toruñ",
                    Address = "Ul. Sk³odowskiej-cuire 84", Email = "torun@zkwp.pl",
                    Telephone = "56-622-30-20",
                    BankAccount = "Pekao SA I O/Toruñ 05 1240 4009 1111 0000 4490 8816" },
                new Organizer { Name = "Wa³brzych", City = "Wa³brzych",
                    Address = "Ul. P³uga 7", Email = "zkwp.walbrzych@gmail.com",
                    Telephone = "74-842-39-96",
                    BankAccount = "BPH SA O/Wa³brzych 21 1060 0076 0000 3200 0125 4537" },
                new Organizer { Name = "Warszawa", City = "Warszawa",
                    Address = "Ul. Lubelska 5/7", Email = "warszawa@zkwp.pl",
                    Telephone = "22-618-25-70",
                    BankAccount = "ING BSK 74 1050 1025 1000 0023 0027 0143" },
                new Organizer { Name = "W³oc³awek", City = "W³oc³awek",
                    Address = "Ul. Starodêbska 26", Email = "wloclawek@zkwp.pl",
                    Telephone = "54-232-64-52",
                    BankAccount = "PKO BP SA O/W³oc³awek 03 1020 5170 0000 1302 0061 5153" },
                new Organizer { Name = "Wroc³aw", City = "Wroc³aw",
                    Address = "Ul. Leszczyñskiego 7", Email = "biuro@zkwp.wroclaw.pl",
                    Telephone = "71-343-25-22",
                    BankAccount = "PKO BP IV O/Wroc³aw 34 1020 5242 0000 2602 0019 8408" },
                new Organizer { Name = "Zabrze", City = "Zabrze",
                    Address = "Ul. Wolnoœci 360", Email = "zabrze@zkwp.pl",
                    Telephone = "32-271-42-80",
                    BankAccount = "Volkswagen Bank Direct 92 2130 0004 2001 0409 0411 0001" },
                new Organizer { Name = "Zakopane", City = "Zakopane",
                    Address = "Ul. Kasprusie 35a", Email = "zkwp-zakopane@o2.pl",
                    Telephone = "18-201-23-28",
                    BankAccount = "PBS 08 8821 0009 0000 0000 0345 0001" },
                new Organizer { Name = "Zielona Góra", City = "Zielona Góra",
                    Address = "Ul. Dêbowskiego 35", Email = "info@zkwp.zgora.pl",
                    Telephone = "68-327-18-55",
                    BankAccount = "PKO II O/Zielona Góra 19 1020 5402 0000 0802 0142 2898" }                    
            };

            organizer.ForEach(o => context.Organizers.AddOrUpdate(a => a.Name, o));
            context.SaveChanges();

            var rank = new List<Rank>
            {
                new Rank { Name = "National" },
                new Rank { Name = "International" }
            };

            rank.ForEach(r => context.Ranks.AddOrUpdate(a => a.Name, r));
            context.SaveChanges();

            var color = new List<Color>
            {
                new Color { NameEN = "Blue-steel", NamePL = "Stalowo-z³oty" },
                new Color { NameEN = "Black", NamePL = "Czarny" },
                new Color { NameEN = "White", NamePL = "Bia³y"  },
                new Color { NameEN = "Smoke", NamePL = "Podpalany" }
            };
            color.ForEach(c => context.Colors.AddOrUpdate(a => a.NameEN, c));
            context.SaveChanges();

            var gender = new List<Gender>
            {
                new Gender { NameEN = "Male", NamePL = "Pies" },
                new Gender { NameEN = "Female", NamePL = "Suka" }
            };
            gender.ForEach(g => context.Genders.AddOrUpdate(a => a.NameEN, g));
            context.SaveChanges();


            var breeds = new List<Breed>
            {
                new Breed { Name = "Australian CattleDog", PkrID = 1},
                new Breed { Name = "Bearded Collie", PkrID = 1},
                new Breed { Name = "Bergamasco", PkrID = 1},
                new Breed { Name = "Bia³y owczarek szwajcarski", PkrID = 1},
                new Breed { Name = "Borded Collie", PkrID = 1},
                new Breed { Name = "Bouvier des Ardennes", PkrID = 1},
                new Breed { Name = "Bouvier des Flandes", PkrID = 1},
                new Breed { Name = "Cao de Serra de Aires", PkrID = 1},
                new Breed { Name = "Ceskoslovensky Vlcak", PkrID = 1},
                new Breed { Name = "Komondor", PkrID = 1},
                new Breed { Name = "Kuvaz", PkrID = 1},
                new Breed { Name = "Maremmano-Abruzzese", PkrID = 1},
                new Breed { Name = "Mudi", PkrID = 1},
                new Breed { Name = "Owczarek australijski - Kelpie", PkrID = 1},
                new Breed { Name = "Owczarek australijski(typ amerykañski)", PkrID = 1},
                new Breed { Name = "Owczarek belgijski - Groenendael", PkrID = 1},
                new Breed { Name = "Owczarek belgijski - Laekenois", PkrID = 1},
                new Breed { Name = "Owczarek belgijski - Malinois", PkrID = 1},
                new Breed { Name = "Owczarek belgijski - Tervurern", PkrID = 1},
                new Breed { Name = "Owczarek chorwacki", PkrID = 1},
                new Breed { Name = "Owczarek francuski Beauceron", PkrID = 1},
                new Breed { Name = "Owczare kfrancuski Briard", PkrID = 1},
                new Breed { Name = "Owczarek holenderski d³ugow³osy", PkrID = 1},
                new Breed { Name = "Owczarek holenderski krótkow³osy", PkrID = 1},
                new Breed { Name = "Owczarek holenderski szkorstkow³osy", PkrID = 1},
                new Breed { Name = "Owczarek kataloñski d³gow³osy", PkrID = 1},
                new Breed { Name = "Owczarek kataloñski g³adkow³osy", PkrID = 1},
                new Breed { Name = "Owczarek niemiecki d³ugow³osy", PkrID = 1},
                new Breed { Name = "Owczarek niemiecki krótkow³osy", PkrID = 1},
                new Breed { Name = "Owczarek pikardyjski", PkrID = 1},
                new Breed { Name = "Owczarek pierenejski ( a face rase)", PkrID = 1},
                new Breed { Name = "Owczarek pirenejski ( a poil long)", PkrID = 1},
                new Breed { Name = "Owczarek podhalañski", PkrID = 1},
                new Breed { Name = "Owczarek po³udnioworosyjski Ju¿ak", PkrID = 1},
                new Breed { Name = "Owczarek staroangielski Bobtail", PkrID = 1},
                new Breed { Name = "Owczarek szetlandzki", PkrID = 1},
                new Breed { Name = "Owczarek szkocki d³ugow³osy", PkrID = 1},
                new Breed { Name = "Owczarek szkocki krótkow³osy", PkrID = 1},
                new Breed { Name = "Owczarek z Majorki d³ugow³osy", PkrID = 1},
                new Breed { Name = "Owczarek z Majorki krótkow³osy", PkrID = 1},
                new Breed { Name = "Polski owczarek nizinny", PkrID = 1},
                new Breed { Name = "Puli", PkrID = 1},
                new Breed { Name = "Pumi", PkrID = 1},
                new Breed { Name = "Saarlooswolfhund", PkrID = 1},
                new Breed { Name = "Schapendoes", PkrID = 1},
                new Breed { Name = "Slovensky Cuvac", PkrID = 1},
                new Breed { Name = "Welsh Corgi Cordigan", PkrID = 1},
                new Breed { Name = "Welsh Corgi Pembroke", PkrID = 1},

                //---------------------------------
                //--------------GRUPA 2------------
                //---------------------------------
                new Breed { Name = "Aidi", PkrID = 2},
                new Breed { Name = "Anatolian", PkrID = 2},
                new Breed { Name = "Appenzeller", PkrID = 2},
                new Breed { Name = "Bernardyn d³ugow³osy", PkrID = 2},
                new Breed { Name = "Bernardyn krótkow³osy", PkrID = 2},
                new Breed { Name = "Berneñski pies pasterski", PkrID = 2},
                new Breed { Name = "Bokser prêgowany", PkrID = 2},
                new Breed { Name = "Bokser ¿ó³ty", PkrID = 2},
                new Breed { Name = "Broholmer", PkrID = 2},
                new Breed { Name = "Buldog angielski", PkrID = 2},
                new Breed { Name = "Bullmastiff", PkrID = 2},
                new Breed { Name = "Cane Corso Italiano", PkrID = 2},
                new Breed { Name = "Cao de Serra da Estrela pelo comprido", PkrID = 2},
                new Breed { Name = "Cao de Serra da Estrela pelo lizo", PkrID = 2},
                new Breed { Name = "Cao Fila de Sao Miguel", PkrID = 2},
                new Breed { Name = "Czarny terier rosyjski", PkrID = 2},
                new Breed { Name = "Doberman", PkrID = 2},
                new Breed { Name = "Dog argentyñski", PkrID = 2},
                new Breed { Name = "Dog kanaryjski", PkrID = 2},
                new Breed { Name = "Dog niemiecki arlekin", PkrID = 2},
                new Breed { Name = "Dog niemiecki b³êkitny", PkrID = 2},
                new Breed { Name = "Dog niemiecki czarny", PkrID = 2},
                new Breed { Name = "Dog niemiecki prêgowany", PkrID = 2},
                new Breed { Name = "Dog niemiecki ¿ó³ty", PkrID = 2},
                new Breed { Name = "Dog z Majorki", PkrID = 2},
                new Breed { Name = "Dogue de Bordeaux", PkrID = 2},
                new Breed { Name = "Du¿y szwajcarski pies pasterski", PkrID = 2},
                new Breed { Name = "Entlebucher", PkrID = 2},
                new Breed { Name = "Fila Brasileiro", PkrID = 2},
                new Breed { Name = "Hollandse Smoushond", PkrID = 2},
                new Breed { Name = "Hovawart", PkrID = 2},
                new Breed { Name = "Kraski Ovcar", PkrID = 2},
                new Breed { Name = "Landseer ( typ kontynentalno=europejski", PkrID = 2},
                new Breed { Name = "Leonberger", PkrID = 2},
                new Breed { Name = "Mastif angielski", PkrID = 2},
                new Breed { Name = "Mastif hiszpañski", PkrID = 2},
                new Breed { Name = "Mastif neapolitañski", PkrID = 2},
                new Breed { Name = "Mastif pirenejski", PkrID = 2},
                new Breed { Name = "Mastif tybetañski", PkrID = 2},
                new Breed { Name = "Nowofundland", PkrID = 2},
                new Breed { Name = "Owczarek kaukaski", PkrID = 2},
                new Breed { Name = "Owczarek œrodkowoazjatycki", PkrID = 2},
                new Breed { Name = "Pinczer austriacki", PkrID = 2},
                new Breed { Name = "Pinczer ma³pi", PkrID = 2},
                new Breed { Name = "Pinczer miniaturowy", PkrID = 2},
                new Breed { Name = "Pinczer œredni", PkrID = 2},
                new Breed { Name = "Pirenejski pies górski", PkrID = 2},
                new Breed { Name = "Rafeiro do Alentejo", PkrID = 2},
                new Breed { Name = "Rottweiler", PkrID = 2},
                new Breed { Name = "Sarplaninac", PkrID = 2},
                new Breed { Name = "Shar Pei", PkrID = 2},
                new Breed { Name = "Sznaucer miniaturowy bia³y", PkrID = 2},
                new Breed { Name = "Sznaucer miniaturowy czarno-srebrny", PkrID = 2},
                new Breed { Name = "Sznaucer miniaturowy czarny", PkrID = 2},
                new Breed { Name = "Sznaucer miniaturowy pieprz i sól", PkrID = 2},
                new Breed { Name = "Sznaucer olbrzym czarny", PkrID = 2},
                new Breed { Name = "Sznaucer olbrzym pieprz i sól", PkrID = 2},
                new Breed { Name = "Sznaucer œredni czarny", PkrID = 2},
                new Breed { Name = "Sznaucer œredni pieprz i sól", PkrID = 2},
                new Breed { Name = "Tosa", PkrID = 2},
                new Breed { Name = "Airedale Terrier", PkrID = 3},
                new Breed { Name = "American Staffordshire Terrier", PkrID = 3},
                new Breed { Name = "Australian Silky Terrier", PkrID = 3},
                new Breed { Name = "Bedlington Terrier", PkrID = 3},
                new Breed { Name = "Bulterier", PkrID = 3},
                new Breed { Name = "Bulterier miniaturowy", PkrID = 3},
                new Breed { Name = "Cairn Terrier", PkrID = 3},
                new Breed { Name = "Dandie Dinmont Terrier", PkrID = 3},
                new Breed { Name = "English Toy Terrier", PkrID = 3},
                new Breed { Name = "Foksterier krótkow³osy", PkrID = 3},
                new Breed { Name = "Foksterier szorstkow³osy", PkrID = 3},
                new Breed { Name = "Irish Glen of Imaal Terrier", PkrID = 3},
                new Breed { Name = "Irish Soft Coated Wheaten Terrier", PkrID = 3},
                new Breed { Name = "Jack Russell Terrier", PkrID = 3},
                new Breed { Name = "Kerry Blue Terrier", PkrID = 3},
                new Breed { Name = "Lakeland Terrier", PkrID = 3},
                new Breed { Name = "Manchester Terrier", PkrID = 3},
                new Breed { Name = "Niemiecki terier myœliwski", PkrID = 3},
                new Breed { Name = "Nihon Teria", PkrID = 3},
                new Breed { Name = "Norfolk Terrier", PkrID = 3},
                new Breed { Name = "Norwich Terrier", PkrID = 3},
                new Breed { Name = "Parson Russell Terrier", PkrID = 3},
                new Breed { Name = "Sealyham Terrier", PkrID = 3},
                new Breed { Name = "Skye Terrier", PkrID = 3},
                new Breed { Name = "Staffordshire Bull Terrier", PkrID = 3},
                new Breed { Name = "Terier australijski", PkrID = 3},
                new Breed { Name = "Terier brazylijski", PkrID = 3},
                new Breed { Name = "Terier czeski", PkrID = 3},
                new Breed { Name = "Terier irlandzki", PkrID = 3},
                new Breed { Name = "Terier szkocki", PkrID = 3},
                new Breed { Name = "Terier walijski", PkrID = 3},
                new Breed { Name = "West Highland White Terrier", PkrID = 3},
                new Breed { Name = "Yorkshire Terrier", PkrID = 3},
                new Breed { Name = "Jamnik krótkow³osy standardowy", PkrID = 4},
                new Breed { Name = "Jamnik d³ugow³osy standardowy", PkrID = 4},
                new Breed { Name = "Jamnik szorstkow³osy standardowy", PkrID = 4},
                new Breed { Name = "Jamnik krótkow³osy miniaturowy", PkrID = 4},
                new Breed { Name = "Jamnik d³ugow³osy miniaturowy", PkrID = 4},
                new Breed { Name = "Jamnik szorstkow³osy miniaturowy", PkrID = 4},
                new Breed { Name = "Jamnik krótkow³osy króliczy", PkrID = 4},
                new Breed { Name = "Jamnik d³ugow³osy króliczy", PkrID = 4},
                new Breed { Name = "Jamnik szorstkow³osy króliczy", PkrID = 4},
                new Breed { Name = "Akita", PkrID = 5},
                new Breed { Name = "Akia amerykañska", PkrID = 5},
                new Breed { Name = "Alaskan Malamute", PkrID = 5},
                new Breed { Name = "Basenji", PkrID = 5},
                new Breed { Name = "Canaan Dog", PkrID = 5},
                new Breed { Name = "Chow Chow", PkrID = 5},
                new Breed { Name = "Cirenco dell'Etna", PkrID = 5},
                new Breed { Name = "Elkhund czarny", PkrID = 5},
                new Breed { Name = "Elkhund szary", PkrID = 5},
                new Breed { Name = "Eurasier", PkrID = 5},
                new Breed { Name = "Hokkaido", PkrID = 5},
                new Breed { Name = "Islandzki szpic pasterski", PkrID = 5},
                new Breed { Name = "Jamthund", PkrID = 5},
                new Breed { Name = "Kai", PkrID = 5},
                new Breed { Name = "Karelski pies na niedŸwiedzie", PkrID = 5},
                new Breed { Name = "Kishu", PkrID = 5},
                new Breed { Name = "Korea Jindo Dog", PkrID = 5},
                new Breed { Name = "Lapinporokoira", PkrID = 5},
                new Breed { Name = "£ajka rosyjsko-europejska", PkrID = 5},
                new Breed { Name = "£ajka wschodniosyberyjska", PkrID = 5},
                new Breed { Name = "£ajka zachodniosyberyjska", PkrID = 5},
                new Breed { Name = "Nagi pies meksykañski miniaturowy", PkrID = 5},
                new Breed { Name = "Nagi pies meksykañski standard", PkrID = 5},
                new Breed { Name = "Nagi pies meksykañski œredni", PkrID = 5},
                new Breed { Name = "Nagi pies peruwiañski du¿y", PkrID = 5},
                new Breed { Name = "Nagi pies peruwiañski miniaturowy", PkrID = 5},
                new Breed { Name = "Nagi pies peruwiañski œredni", PkrID = 5},
                new Breed { Name = "Norrbottenspets", PkrID = 5},
                new Breed { Name = "Norsk Buthund", PkrID = 5},
                new Breed { Name = "Norsk Lundehund", PkrID = 5},
                new Breed { Name = "Pies Faraona", PkrID = 5},
                new Breed { Name = "Pies grenlandzki", PkrID = 5},
                new Breed { Name = "Podenco kanaryjski", PkrID = 5},
                new Breed { Name = "Podenco z Ibizy krótkow³osy", PkrID = 5},
                new Breed { Name = "Podenco z Ibizy szorstkow³osy", PkrID = 5},
                new Breed { Name = "Podengo portugalski szorstkow³osy du¿y", PkrID = 5},
                new Breed { Name = "Podengo portugalski szorstkow³osy œredni", PkrID = 5},
                new Breed { Name = "Podengo protugalski szorstkow³osy miniaturowy", PkrID = 5},
                new Breed { Name = "Podengo postugalski krótkow³osy du¿y", PkrID = 5},
                new Breed { Name = "Podengo portugalski krótkow³osy œredni", PkrID = 5},
                new Breed { Name = "Podengo portugalski krótkow³osy miniaturowy", PkrID = 5},
                new Breed { Name = "Samoyed", PkrID = 5},
                new Breed { Name = "Shiba", PkrID = 5},
                new Breed { Name = "Shikoku", PkrID = 5},
                new Breed { Name = "Siberian Husky", PkrID = 5},
                new Breed { Name = "Suomenlapinkoira", PkrID = 5},
                new Breed { Name = "Svensk Lapphund", PkrID = 5},
                new Breed { Name = "Szpic du¿y bia³y", PkrID = 5},
                new Breed { Name = "Szpic du¿y kolorowy", PkrID = 5},
                new Breed { Name = "Szpic fiñski", PkrID = 5},
                new Breed { Name = "Szpic japoñski", PkrID = 5},
                new Breed { Name = "Szpic ma³y bia³y", PkrID = 5},
                new Breed { Name = "Szpic ma³y kolorowy klasyczny", PkrID = 5},
                new Breed { Name = "Szpic ma³y kolorowy wspólczesny", PkrID = 5},
                new Breed { Name = "Szpic miniaturowy", PkrID = 5},
                new Breed { Name = "Szpic œredni bia³y", PkrID = 5},
                new Breed { Name = "Szpic œredni klasyczny", PkrID = 5},
                new Breed { Name = "Szpic œrednio kolorowy wspó³czesny", PkrID = 5},
                new Breed { Name = "Szpic wilczy", PkrID = 5},
                new Breed { Name = "Szpic w³oski", PkrID = 5},
                new Breed { Name = "Thai Ridgeback Dog", PkrID = 5},
                new Breed { Name = "Vastgotaspets", PkrID = 5},
                new Breed { Name = "Alpejski goñczy krótkono¿ny", PkrID = 6},
                new Breed { Name = "Ariegeois", PkrID = 6},
                new Breed { Name = "Basset artezyjsko-normandzki", PkrID = 6},
                new Breed { Name = "Basset bretoñski", PkrID = 6},
                new Breed { Name = "Basset gaskoñski", PkrID = 6},
                new Breed { Name = "Basset Hound", PkrID = 6},
                new Breed { Name = "Beagle", PkrID = 6},
                new Breed { Name = "Beagle-Harrier", PkrID = 6},
                new Breed { Name = "Billy", PkrID = 6},
                new Breed { Name = "Black and Tan Coonhound", PkrID = 6},
                new Breed { Name = "Bloodhund", PkrID = 6},
                new Breed { Name = "Cien d'Artois", PkrID = 6},
                new Breed { Name = "Dalmatyñczyk", PkrID = 6},
                new Breed { Name = "Drever", PkrID = 6},
                new Breed { Name = "Dunker", PkrID = 6},
                new Breed { Name = "Du¿y goñczy anglo-francuski bia³o-czarny", PkrID = 6},
                new Breed { Name = "Du¿y goñczy anglo-francuski bia³o-pomarañczony", PkrID = 6},
                new Breed { Name = "Du¿y goñczy anglo-francuski trójkolorowy", PkrID = 6},
                new Breed { Name = "Du¿y goñczy gaskoñski", PkrID = 6},
                new Breed { Name = "Foxhound amerykañski", PkrID = 6},
                new Breed { Name = "Foxhound angielski", PkrID = 6},
                new Breed { Name = "Goñczy austriacki - Brandlbracke", PkrID = 6},
                new Breed { Name = "Goñczy berneñski", PkrID = 6},
                new Breed { Name = "Goñczy berneñski krótkono¿ny krótkow³osy", PkrID = 6},
                new Breed { Name = "Goñczy berneñski krótkono¿ny szorstkow³osy", PkrID = 6},
                new Breed { Name = "Goñczy boœniacki szorstkow³osy Barak", PkrID = 6},
                new Breed { Name = "Goñczy chorwacki", PkrID = 6},
                new Breed { Name = "Goñczy fiñski", PkrID = 6},
                new Breed { Name = "Goñczy francuski bia³o-czarny", PkrID = 6},
                new Breed { Name = "Goñczy francuski bia³o-pomarañczowy", PkrID = 6},
                new Breed { Name = "Goñczy francuski trójkolorowy", PkrID = 6},
                new Breed { Name = "Goñczy grecki", PkrID = 6},
                new Breed { Name = "Goñczy Hamiltona", PkrID = 6},
                new Breed { Name = "Goñczy hiszpañski", PkrID = 6},
                new Breed { Name = "Goñczy istryjski krótkow³osy", PkrID = 6},
                new Breed { Name = "Goñczy istryjski szorstkow³osy", PkrID = 6},
                new Breed { Name = "Goñczy jugos³owiañski trójkolorowy", PkrID = 6},
                new Breed { Name = "Goñczy lucereñski", PkrID = 6},
                new Breed { Name = "Goñczy lucereñski krótkono¿ny", PkrID = 6},
                new Breed { Name = "goñczy niemiecki", PkrID = 6},
                new Breed { Name = "Goñczy Schillera", PkrID = 6},
                new Breed { Name = "Goñczy serbski", PkrID = 6},
                new Breed { Name = "Goñczy s³owacki", PkrID = 6},
                new Breed { Name = "Goñczy smalandzki", PkrID = 6},
                new Breed { Name = "Goñczy stryjski", PkrID = 6},
                new Breed { Name = "Goñczy szwajcarski", PkrID = 6},
                new Breed { Name = "Goñczy tyrolski", PkrID = 6},
                new Breed { Name = "Goñczy wêgierski", PkrID = 6},
                new Breed { Name = "Goñczy w³oski krótkow³osy", PkrID = 6},
                new Breed { Name = "Goñczy w³oski szorstkow³osy", PkrID = 6},
                new Breed { Name = "Goñczy z Jury", PkrID = 6},
                new Breed { Name = "Goñczy z Jury krótkono¿ny", PkrID = 6},
                new Breed { Name = "Goñczy ze Schwyz", PkrID = 6},
                new Breed { Name = "Goñczy ze Schwyz krótkono¿ny", PkrID = 6},
                new Breed { Name = "Goñczy Basset griffon vendeen", PkrID = 6},
                new Breed { Name = "Grand gascon saintongeois", PkrID = 6},
                new Breed { Name = "Grand griffon vendeen", PkrID = 6},
                new Breed { Name = "Haldenstovare", PkrID = 6},
                new Breed { Name = "Harrier", PkrID = 6},
                new Breed { Name = "Hygenhund", PkrID = 6},
                new Breed { Name = "Jugos³owiañski goñczy górski", PkrID = 6},
                new Breed { Name = "Ma³y goñczy anglo-francuski", PkrID = 6},
                new Breed { Name = "Ma³y goñczy gaskoñski", PkrID = 6},
                new Breed { Name = "Ogar polski", PkrID = 6},
                new Breed { Name = "Otterbound", PkrID = 6},
                new Breed { Name = "Petit Basset griffon vendeen", PkrID = 6},
                new Breed { Name = "Petit gascon saintongeois", PkrID = 6},
                new Breed { Name = "Poitevin", PkrID = 6},
                new Breed { Name = "Porcelaine", PkrID = 6},
                new Breed { Name = "Posokowiec bawarki", PkrID = 6},
                new Breed { Name = "Posokowiec hanowerski", PkrID = 6},
                new Breed { Name = "Rhiodesian Ridgeback", PkrID = 6},
                new Breed { Name = "Szorskow³osy goñczy bretoñski", PkrID = 6},
                new Breed { Name = "Szorstkow³osy goñczy gaskoñski", PkrID = 6},
                new Breed { Name = "Szorstkow³osy goñczy wandejski", PkrID = 6},
                new Breed { Name = "Szorstkow³osy goñczy z Nivernais", PkrID = 6},
                new Breed { Name = "Westfalski goñczy krótkono¿ny", PkrID = 6},
                new Breed { Name = "", PkrID = 7},
                new Breed { Name = "", PkrID = 7},
                new Breed { Name = "", PkrID = 7},
                new Breed { Name = "", PkrID = 7},
                new Breed { Name = "", PkrID = 7},
                new Breed { Name = "", PkrID = 7},
                new Breed { Name = "", PkrID = 7},
                new Breed { Name = "", PkrID = 7},
                new Breed { Name = "", PkrID = 7},
                new Breed { Name = "", PkrID = 7},
                new Breed { Name = "", PkrID = 7},
                new Breed { Name = "", PkrID = 7},
                new Breed { Name = "", PkrID = 7},
                new Breed { Name = "", PkrID = 7},

            };

            breeds.ForEach(b => context.Breeds.AddOrUpdate(p => p.Name, b));
            context.SaveChanges();
        }
    }
}
